name: Ubuntu 22.04 CI (GCC 11)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use cmake
        run: |
          cd test && make && ./unit
